//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Autos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autos()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int AutoID { get; set; }
        [DisplayName("Année de la voiture :")]
        public string Year { get; set; }
        public string Marque { get; set; }
        public string Model { get; set; }
        public int Vehicle_Nbre { get; set; }
        [DisplayName("Voitue Louée ou Financée :")]
        public string IsLeqsedOrFinanced { get; set; }
        public string Vehicle_Use { get; set; }
        [DisplayName("Nombre de kilométrage :")]
        public double KilometersPerYear { get; set; }
        public int Infraction_Nbre { get; set; }
        public int Accident_Nbre { get; set; }
        [DisplayName("Type de Réclamation s'il y a eu lieu :")]
        public string Claim_Type { get; set; }
        [DisplayName("Date de Réclamation s'il y a eu lieu :")]
        [DataType(DataType.Date)]
        public System.DateTime Date_Of_Claim { get; set; }
        [DisplayName("Le coût de la soumission par mois $ :")]
        public double Estimation_Per_Month { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
