//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "User Name is required")]
        [DisplayName("Prénom :")]
        public string First_Name { get; set; }
        [Required]
        [DisplayName("Nom :")]
        public string Last_Name { get; set; }
        [Required]
        [DisplayName("Etat matrimonial :")]
        public string Civility { get; set; }

        [DisplayName("Date de naissance :")]
        [DataType(DataType.Date), Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Birthdate { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> HabitationID { get; set; }
        public Nullable<int> AutoID { get; set; }
        [DisplayName("Type d'assurance :")]
        [Required]
        public string Type_Of_insurance { get; set; }
        [Required]
        [DisplayName("Genre :")]
        public string Sexe { get; set; }
        public Nullable<int> ContactID { get; set; }
        public  Addresses Addresses { get; set; }
        public Autos Autos { get; set; }
        public  Contacts Contacts { get; set; }
        public  Habitations Habitations { get; set; }
    }
}
