//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitations()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int HabitationID { get; set; }
        public int Unit_Nbre { get; set; }
        public string Protect_Device { get; set; }
        public bool isHadPropertyInsurance { get; set; }
        public System.DateTime ExpiryPropertyInsurance { get; set; }
        public string Claims_Nbre { get; set; }
        public string Claim_Type { get; set; }
        public System.DateTime Date_Of_Claim { get; set; }
        public bool SewerBackupInsurance { get; set; }
        public double Estimation_Per_Month { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
